### ISSUE TITLE
Transpiled index.cjs.js misses export = merge;

### ISSUE THREAD

**Issue by casdevs** [mesqueeb/merge-anything#2]
When using your lib from native node.js ESM code (node.js >= 12 with --experimental-modules enabled),
```
import merge from 'merge-anything';
merge();
```
yields `TypeError: merge is not a function`

This is because the transpiled `dist/index.cjs.js` misses an `export = merge` statement (in constrast to e.g. your `copy-anything/dist/index.cjs.js`'s correctly including  a `module.exports = copy;` line.)

Maybe you can adjust your transpiler config to fix that? I'm not that familiar with rollup...

Thanks!

**Comment by mesqueeb** [comment]
@casdevs thanks so much for this issue.
I've been looking into it, but i'm so confused why this is happening.

merge-anything has destructible exports as well as a default. copy-anything only has a default. but I'm not sure this is the reason for this problem.

One other thing I found in merge-anything that I didn't in copy-anything is this line:
https://github.com/mesqueeb/merge-anything/blob/master/dist/index.cjs.js#L3

I've tried googling this, but I'm still confused on what this line does and why rollup is adding this to my cjs build.

If you have any advice for me please let me know. 😄

**Comment by casdevs** [comment]
seems to be complicated to achieve this with rollup...
see https://github.com/rollup/rollup/issues/1961 for details

At the moment, it doesn't seem possible to import your module with using the same source code in both native ESM node.js as well as in babel transpiling environment

possible solutions
* https://github.com/rollup/rollup/issues/1961#issuecomment-534977678 (rather hackish indeed)
* https://stackoverflow.com/questions/58246998/mixing-default-and-named-exports-with-rollup

Maybe someone has an idea how to solve this elegantly.

**Comment by mesqueeb** [comment]
@casdevs
I think in the meanwhile, you use `import { merge } from 'merge-anything'` instead. 😉 

So I understand now that the reason is because I have mixed default and named exports. I have to do this to support the plugins though. Unless I externalise the plugins into another library, which I don't really wanna do now...

I'll see if there's other solutions and if I find one I'll comment here. Let's just keep this issue open. But I don't think there'll be a solution any time soon.

**Comment by casdevs** [comment]
> I think in the meanwhile, you use `import { merge } from 'merge-anything'` instead. wink

unfortunately, when importing CJS (which is the default module format at the moment in your project) modules via `import` from native ES modules, importing named exports is not possible.
You can only import the default export, which - in `merge-anything`'s case - is not defined in the CJS module...

so I'm currently doing a compatibility workaround
```
import mergeAnything from 'merge-anything';

// this is required to work for both native node.js ESM callers and babel-transpiling-ESM-to-CJS callsers
const merge = mergeAnything.default || mergeAnything;
```

Has anyone an opinion on whether there are any disadvantages of simply adding a line
`
export = merge;
`
in the transpiled `dist/index.cjs.js` file of `merge-anything`?

**Comment by mesqueeb** [comment]
@casdevs 
Currently it says:
```js
exports.merge = merge;
exports.concatArrays = concatArrays;
exports.default = merge;
```
When I check the difference with [copy-anything](https://github.com/mesqueeb/copy-anything/blob/master/dist/index.cjs.js#L48) I see it just says:
```js
module.exports = copy;
```

If the modern ESM module only has a default export, it seems to me that the CJS module will set the entire `module.exports` object to be the exported variable.

When there's a mix between named and default, I cannot set `module.exports = merge;` because it will nullify the named exports. (and thus the named export `concatArrays` cannot be accessed anymore)

That means that you'll be able to import the library via `mergeAnything.default` as you say.
I think for nodeJS which uses the CJS syntax, the import method would be:
```js
const merge = require('merge-anything').default
```

The weird thing is that you say:
> "importing CJS modules via import from native ES modules"

Because it is my understanding that rollup & webpack look at the "module" field of the package.json. Which in my case [points to the esm file](https://github.com/mesqueeb/merge-anything/blob/master/package.json#L6) - and not the CJS one.

Can you let me know a bit about your specific setup and environment? Because I was under the impression that tools that use modern esm style import and export will automatically use the `.esm.js` file I had prepared. Yet in your case this doesn't seem to be the case.

**Comment by casdevs** [comment]
> Because it is my understanding that rollup & webpack look at the "module" field of the package.json. Which in my case [points to the esm file](https://github.com/mesqueeb/merge-anything/blob/master/package.json#L6) - and not the CJS one.

you're right, that's the way it works when using a transpiler.

However, in native ESM node.js mode (--experimental-modules in node.js 12 or without this flag in node.js >= 13.2), using named imports from "legacy" CJS modules is not possible, you can only use the default export. Non-standard things like "module" field in package.json are not evaluated by native native ESM node.js.

So you have two choices:
* either make your package a true Dual CommonJS/ES Module one (see https://nodejs.org/api/esm.html#esm_dual_commonjs_es_module_packages for how to achieve that) OR
* ensure that your code transpiled to CJS also sets a valid default export (which I think can be achived by doing
```
exports = merge; <-- THIS MAYBE CAN BE INSERTED BY ROLLUP USING THE HACK LINKED IN MY PREVIOUS COMMENT
exports.merge = merge;
exports.concatArrays = concatArrays;
exports.default = merge;
```

I would rather go with the (more future-proof) first choice...

**Comment by mesqueeb** [comment]
@casdevs 
Based on the nodeJS documentation you shared, I tried something that I believe should work in your case.
Can you try to install the latest version (v2.4.3) and let me know how it goes?

Your node (with the flags) _should_ now point to the ESM file instead of the CJS one.
Therefore you should be able to do both
- `import { merge } from 'merge-anything'` _and_
- `import merge from 'merge-anything'`

**Comment by robbtraister** [comment]
FYI, this most recent change has broken [styled-components](https://www.npmjs.com/package/styled-components) (and any other require-based import) on node 13.

**Comment by mesqueeb** [comment]
@robbtraister did my latest commit but oak something?
I only added some fields to package.json. 
Can you elaborate a bit further on how this was used with styled components and what broke exactly?
I'd have to see if I need to revert the change or if I should find another solution. 😅

Much appreciated !!  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maiopirata** [comment]
I confirm I have the same problem as @robbtraister when using 2.4.3. I think it breaks styled-components.
The error message is not so clear though.
```
No valid exports main found for '/Users/[]/Documents/Cloud/[]/node_modules/merge-anything'
@taxier/ui:     at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)
```
Tomorrow I will have a much closer look and I will comment here

**Comment by mesqueeb** [comment]
@maiopirata @robbtraister @matoous @stevenpray I have reverted to the previous package.json export method in 2.4.4.

It's weird because the only difference was an addition of these lines:

<img width="322" alt="image" src="https://user-images.githubusercontent.com/3253920/70013790-17780d00-15bc-11ea-94c7-39e3cd311920.png">

@casdevs 
Can you confirm how the package works in your environment in 2.4.3 ?

**Comment by maiopirata** [comment]
So after my message yesterday night I tried to erase the 'type' and 'exports' field inside package json exactly as you did in the new release 2.4.4.
It works.

So I come across this because I'm "updating" the dependencies of a project.
I've updated node from v10 to v13 last stable release. So I haven't checked but this problem should be related to node>12 that supports the new 'type': 'module' thing.
Maybe this can be related https://github.com/standard-things/esm/issues/784

Hope it can help understand the root cause

**Comment by robbtraister** [comment]
I tried to research this a bit yesterday. I'm not sure if this is exactly correct, but my understanding is the following:

- in order to use named exports in node, you have to use `"type": "module"` (as you did)
- once you have designated `"type": "module"`, importing with `require` is flagged as deprecated in node 12 and throws in node 13
- the only way to restore `require` imports in node 13 is by using conditional exports (as you did)
- BUT conditional exports are only respected with the `--experimental-conditional-exports` flag
- and even with the conditional export flag, the commonjs file must have a `.cjs` extension and the values in the `"exports"` object must be relative (i.e., start with `./`)

After modifying the package inside my `node_modules` folder with the above changes (remove the excess `.js` extension from the commonjs build artifact and prepend `./` to the values in the `"exports"` object), I was able to run 2.4.3 with the `--experimental-conditional-exports` flag on node 13.

I think the question going forward is whether you want to support named exports or node 13 without the use of the conditional export flag, since they seem to be mutually exclusive.

**Comment by casdevs** [comment]
sorry for the delay.

I've tested your 2.4.3 version in node.js with --experimental-modules flag enabled and got the error `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/node/app/dist/index.cjs.js`. Reason is you've just changed the default module format of your package to ESM in your 2.4.3 version, without adapting the main entry point. So before releasing such small changes with big impact, I would always prefer to test in the targeted environments first ;-)
If you do not have node 13.2 (where the --experimental-modules is now unflagged), you can at least use node 12 LTS and do an `export NODE_OPTIONS=--experimental-modules` before running your build/test script to see if everything works as expected. If done right, your build/test should run successfully with and without the flag in node 12 LTS.

Another good site describing the possibilities how to provide hybrid CJS/ESM packages is
https://2ality.com/2019/10/hybrid-npm-packages.html

Maybe `Solution 2.1 Option 1 (experimental, needs conditional exports): ESM and CommonJS are both bare imports` (see https://2ality.com/2019/10/hybrid-npm-packages.html#option-1-(experimental%2C-needs-conditional-exports)%3A-esm-and-commonjs-are-both-bare-imports) is an option that is both backwards-compatible and allows named imports in Node 13.2 if someone enables the conditional-exports flag.

Seems a definitive, optimal way of how to provide hybrid CJS/ESM packages hasn't settled yet...

**Comment by casdevs** [comment]
that being said, maybe it is (currently) a better solution to simply have rollup.js **prepend** the missing `export = merge;` line, so default **and** named imports both work in CJS **and** ESM environments.

**Comment by mesqueeb** [comment]
To everyone here.
I believe the problem comes from **using both a default export and named exports**.

I am thinking of updating the package to version 3.0 with the breaking change that it will **only have named exports**. That means that you can only write `import { merge } from 'merge-anything'` but it will work in all environments.

I thought about other solutions but they all felt "hacky". And I've tried to research a lot about this problem, but the root of the problem at hand remained not 100% clear to me. Currently the market seems to be very divided because of all the bundle methods; nodeJS versions; and possible environments. 😄 

In fact, most articles and documentation I read all recommend to **not mix default and named exports**! So I believe that I should adopt that habit and it will only be beneficial. I realise using only named exports will also better help with tree-shaking of the package.

If there are no objections I will do this in about 1 week.

**Comment by casdevs** [comment]
seems reasonable to me!

**Comment by mesqueeb** [comment]
To everyone here!
I have just updated merge-anything to version 3.0, which now **only has named exports**!

(it should resolve this issue)

Please see the release notes here:
https://github.com/mesqueeb/merge-anything/releases/tag/v3.0
