### ISSUE TITLE
`interface` does not satisfy `Record<string | number | symbol, unknown>`

### ISSUE THREAD

**Issue by lukeshay** [mesqueeb/merge-anything#33]
In TypeScript, interfaces do not satisfy the type `Record<string | number | symbol, unknown>` which is not what the functions are expecting. Here is a minimal example:

```ts
import { merge } from "merge-anything";

interface Arguments {
    key: string;
}

merge<Arguments, Arguments[]>({ key: "value1" }, { key: "value2" });
```

<img width="818" alt="image" src="https://user-images.githubusercontent.com/38476395/201696487-2bf9d78e-99af-457a-a67d-bc5f600fa51a.png">

**Comment by mesqueeb** [comment]
@lukeshay I tried to make this work for about 2 hours, but could only find one solution.

please change 
```ts
interface Arguments {
    key: string;
}
```
to
```ts
interface Arguments extends Record<string | number | symbol, unknown> {
    key: string;
}
```
and then it works!

I personally always prefer to use `type` over `interface` and would suggest this for you as well:

```ts
type Arguments = {
    key: string;
}
```

I'm sure some dev teams have other ideas though and therefore this is not ideal, but I'm not sure how to tweak the `merge-anything` types otherwise.
Please let me know if you have other ideas for me.

**Comment by mesqueeb** [comment]
@lukeshay It finally hit me. I can default to your interface type like this:

```ts
export function merge<T, Tn extends unknown[]>(
  object: T,
  ...otherObjects: Tn
): T extends Record<string | number | symbol, unknown>
  ? Tn extends Record<string | number | symbol, unknown>[]
    ? Merge<T, Tn>
    : T
  : T
```

this way you can just do:
```ts
interface Arguments {
  key: string
}
const a1: Arguments = { key: 'value1' }
const a2: Arguments = { key: 'value2' }
const a = merge(a1, a2)
```
and it should work without issues!

Do you like this approach?
